# Generated by Django 4.1.2 on 2022-10-13 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accelaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueX', models.FloatField(default=0)),
                ('valueY', models.FloatField(default=0)),
                ('valueZ', models.FloatField(default=0)),
                ('sensor_name', models.TextField(default='Accelaration', max_length=100)),
                ('description', models.TextField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueX', models.FloatField(default=0)),
                ('valueY', models.FloatField(default=0)),
                ('valueZ', models.FloatField(default=0)),
                ('sensor_name', models.TextField(default='Rotation', max_length=100)),
                ('description', models.TextField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', max_length=100)),
                ('last_name', models.TextField(default='', max_length=100)),
                ('birth', models.DateField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sensor.device')),
            ],
        ),
        migrations.CreateModel(
            name='Gyroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueX', models.FloatField(default=0)),
                ('valueY', models.FloatField(default=0)),
                ('valueZ', models.FloatField(default=0)),
                ('sensor_name', models.TextField(default='Gyroscope', max_length=100)),
                ('description', models.TextField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', max_length=100)),
                ('last_name', models.TextField(default='', max_length=100)),
                ('birth', models.DateField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sensor.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DataSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 13, 21, 5, 1, 560915))),
                ('acceleration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.accelaration')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.device')),
                ('gyroscope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.gyroscope')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.rotation')),
                ('touch_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.touchstatus')),
            ],
        ),
        migrations.AddField(
            model_name='accelaration',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.unit'),
        ),
    ]
