# Generated by Django 4.1.2 on 2022-10-13 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 13, 23, 12, 45, 719884))),
                ('acceleration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.accelaration')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.device')),
                ('gyroscope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.gyroscope')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.rotation')),
                ('touch_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.touchstatus')),
            ],
        ),
        migrations.DeleteModel(
            name='DataSending',
        ),
    ]
