# Generated by Django 4.1.2 on 2022-10-14 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0002_rawdata_delete_datasending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 14, 33, 11, 343864)),
        ),
    ]
